config/routes.rb
Rails.application.routes.draw do
  root 'purchase_orders#index'

  resources :order_items
  resources :items
  resources :purchase_orders
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
    has_many :order_items, dependent: :destroy
  
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
  
    def as_indexed_json(_options = {})
      PurchaseOrderDenormalizer.new(self).to_hash
    end
  
    settings index: { number_of_shards: 1 } do
      mapping dynamic: 'false' do
        indexes :id, type: :integer
        indexes :purchase_date, type: :date, format: :date_optional_time
        indexes :status, type: :keyword
        indexes :sales_channel, type: :keyword
        indexes :num_items_shipped, type: :integer
        indexes :num_items_unshipped, type: :integer
        indexes :payment_method, type: :keyword
        indexes :shipped_at, type: :date, format: :date_optional_time
        indexes :shipping_price, type: :half_float
        indexes :shipping_tax, type: :half_float
        indexes :carrier, type: :keyword
        indexes :tracking_number
        indexes :estimated_arrival_date, type: :date, format: :date_optional_time
        indexes :fulfillment_center, type: :keyword
        indexes :confirmed_at, type: :date, format: :date_optional_time
        indexes :returned_date, type: :date, format: :date_optional_time
        indexes :return_reason
        indexes :notes
        indexes :refunded_at, type: :date, format: :date_optional_time
        indexes :ship_to_name
        indexes :ship_to_address
  
        indexes :skus
        indexes :item_ids, type: :long
  
        indexes :unique_products, type: :integer
        indexes :quantity_ordered, type: :integer
        indexes :quantity_shipped, type: :integer
        indexes :quantity_unshipped, type: :integer
  
        indexes :currency, type: :keyword
  
        indexes :order_items_info, type: :nested do
          indexes :item_id, type: :integer
          indexes :quantity_ordered, type: :integer
          indexes :quantity_shipped, type: :integer
          indexes :price, type: :half_float
          indexes :discount, type: :half_float
          indexes :tax, type: :half_float
          indexes :platform_fee, type: :half_float
  
          # extras
          indexes :item_title
          indexes :item_sku
          indexes :item_nickname
        end
  
      end
    end
  
  end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_action :set_purchase_order, only: %i[ show edit update destroy ]

  # GET /purchase_orders or /purchase_orders.json
  def index
    @purchase_orders = PurchaseOrder.all
  end

  # GET /purchase_orders/1 or /purchase_orders/1.json
  def show
  end

  # GET /purchase_orders/new
  def new
    @purchase_order = PurchaseOrder.new
  end

  # GET /purchase_orders/1/edit
  def edit
  end

  # POST /purchase_orders or /purchase_orders.json
  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)

    respond_to do |format|
      if @purchase_order.save
        format.html { redirect_to purchase_order_url(@purchase_order), notice: "Purchase order was successfully created." }
        format.json { render :show, status: :created, location: @purchase_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_orders/1 or /purchase_orders/1.json
  def update
    respond_to do |format|
      if @purchase_order.update(purchase_order_params)
        format.html { redirect_to purchase_order_url(@purchase_order), notice: "Purchase order was successfully updated." }
        format.json { render :show, status: :ok, location: @purchase_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1 or /purchase_orders/1.json
  def destroy
    @purchase_order.destroy

    respond_to do |format|
      format.html { redirect_to purchase_orders_url, notice: "Purchase order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def purchase_order_params
      params.require(:purchase_order).permit(:order_num, :purchase_date, :status, :sales_channel, :order_total, :num_items_shipped, :num_items_unshipped, :payment_method, :shipped_at, :shipping_price, :shipping_tax, :carrier, :tracking_number, :estimated_arrival_date, :fulfillment_center, :confirmed_at, :returned_date, :return_reason, :notes, :refunded_at, :ship_to_name, :ship_to_address)
    end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/purchase_orders/_form.html.erb
<%= form_with(model: purchase_order) do |form| %>
  <% if purchase_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(purchase_order.errors.count, "error") %> prohibited this purchase_order from being saved:</h2>

      <ul>
        <% purchase_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_num, style: "display: block" %>
    <%= form.text_field :order_num %>
  </div>

  <div>
    <%= form.label :purchase_date, style: "display: block" %>
    <%= form.datetime_field :purchase_date %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :sales_channel, style: "display: block" %>
    <%= form.text_field :sales_channel %>
  </div>

  <div>
    <%= form.label :order_total, style: "display: block" %>
    <%= form.text_field :order_total %>
  </div>

  <div>
    <%= form.label :num_items_shipped, style: "display: block" %>
    <%= form.number_field :num_items_shipped %>
  </div>

  <div>
    <%= form.label :num_items_unshipped, style: "display: block" %>
    <%= form.number_field :num_items_unshipped %>
  </div>

  <div>
    <%= form.label :payment_method, style: "display: block" %>
    <%= form.text_field :payment_method %>
  </div>

  <div>
    <%= form.label :shipped_at, style: "display: block" %>
    <%= form.datetime_field :shipped_at %>
  </div>

  <div>
    <%= form.label :shipping_price, style: "display: block" %>
    <%= form.text_field :shipping_price %>
  </div>

  <div>
    <%= form.label :shipping_tax, style: "display: block" %>
    <%= form.text_field :shipping_tax %>
  </div>

  <div>
    <%= form.label :carrier, style: "display: block" %>
    <%= form.text_field :carrier %>
  </div>

  <div>
    <%= form.label :tracking_number, style: "display: block" %>
    <%= form.text_field :tracking_number %>
  </div>

  <div>
    <%= form.label :estimated_arrival_date, style: "display: block" %>
    <%= form.datetime_field :estimated_arrival_date %>
  </div>

  <div>
    <%= form.label :fulfillment_center, style: "display: block" %>
    <%= form.text_field :fulfillment_center %>
  </div>

  <div>
    <%= form.label :confirmed_at, style: "display: block" %>
    <%= form.datetime_field :confirmed_at %>
  </div>

  <div>
    <%= form.label :returned_date, style: "display: block" %>
    <%= form.datetime_field :returned_date %>
  </div>

  <div>
    <%= form.label :return_reason, style: "display: block" %>
    <%= form.text_field :return_reason %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.label :refunded_at, style: "display: block" %>
    <%= form.datetime_field :refunded_at %>
  </div>

  <div>
    <%= form.label :ship_to_name, style: "display: block" %>
    <%= form.text_field :ship_to_name %>
  </div>

  <div>
    <%= form.label :ship_to_address, style: "display: block" %>
    <%= form.text_field :ship_to_address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/purchase_orders/_purchase_order.html.erb
<div id="<%= dom_id purchase_order %>">
  <tr>
    <td><%= purchase_order.order_num %></td>
    <td><%= purchase_order.purchase_date %></td>
    <td><%= purchase_order.status %></td>
    <td><%= purchase_order.sales_channel %></td>
    <td><%= purchase_order.order_total %></td>
    <td><%= purchase_order.num_items_shipped %></td>
    <td><%= purchase_order.num_items_unshipped %></td>
    <td><%= purchase_order.payment_method %></td>
    <td><%= purchase_order.shipped_at %></td>
    <td><%= purchase_order.shipping_price %></td>
    <td><%= purchase_order.shipping_tax %></td>
    <td><%= purchase_order.carrier %></td>
    <td><%= purchase_order.tracking_number %></td>
    <td><%= purchase_order.estimated_arrival_date %></td>
    <td><%= purchase_order.fulfillment_center %></td>
    <td><%= purchase_order.confirmed_at %></td>
    <td><%= purchase_order.returned_date %></td>
    <td><%= purchase_order.return_reason %></td>
    <td><%= purchase_order.notes %></td>
    <td><%= purchase_order.refunded_at %></td>
    <td><%= purchase_order.ship_to_name %></td>
    <td><%= purchase_order.ship_to_address %></td>
    <td><%= link_to "Show", purchase_order %></td>
  </tr>
</div>

app/views/purchase_orders/edit.html.erb
<h1>Editing purchase order</h1>

<%= render "form", purchase_order: @purchase_order %>

<br>

<div>
  <%= link_to "Show this purchase order", @purchase_order %> |
  <%= link_to "Back to purchase orders", purchase_orders_path %>
</div>

app/views/purchase_orders/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "New purchase order", new_purchase_order_path %>

<h1>Purchase orders</h1>

<div id="purchase_orders">
<table>
  <thead>
    <th>Order num:</th>
    <th>Purchase date:</th>
    <th>Status:</th>
    <th>Sales channel:</th>
    <th>Num items shipped:</th>
    <th>Num items unshipped:</th>
    <th>Payment method:</th>
    <th>Shipped at:</th>
    <th>Shipping price:</th>
    <th>Shipping tax:</th>
    <th>Carrier:</th>
    <th>Tracking number:</th>
    <th>Estimated arrival date:</th>
    <th>Fulfillment center:</th>
    <th>Confirmed at:</th>
    <th>Returned date:</th>
    <th>Return reason:</th>
    <th>Notes:</th>
    <th>Refunded at:</th>
    <th>Ship to name:</th>
    <th>Ship to address:</th>
    <th>Show Order</th>
  </thead>
  <tbody>
    <% @purchase_orders.each do |purchase_order| %>
    <%= render purchase_order %>
  <% end %>
  </tbody>
</div>

app/views/purchase_orders/new.html.erb
<h1>New purchase order</h1>

<%= render "form", purchase_order: @purchase_order %>

<br>

<div>
  <%= link_to "Back to purchase orders", purchase_orders_path %>
</div>

app/views/purchase_orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @purchase_order %>

<div>
  <%= link_to "Edit this purchase order", edit_purchase_order_path(@purchase_order) %> |
  <%= link_to "Back to purchase orders", purchase_orders_path %>

  <%= button_to "Destroy this purchase order", @purchase_order, method: :delete %>
</div>